### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by newbialywhodis** [Nitesam/ns_houserobbery#1]
Hello, i tried to test your script, but im getting error if i want to enter house 
```main.lua:69: attempt to call a nil value (field 'TableCopy')```
How do i can fix it?

**Comment by Nitesam** [comment]
Hi!
Yeah my bad, i completely forgot to use another method to copy that table, i'm gonna push a fix right now, thank you.

**Comment by newbialywhodis** [comment]
No problemo, i didnt reach main feature of your script - but i feel like it might be really good release, also - Im changing notifys right now to ox_lib

**Comment by Nitesam** [comment]
i've made a push to fix the problem, just copy this function at the end of your config.lua file and update server/main.lua!

```
function TableCopy(orig)
	local orig_type, copy = type(orig)

    if orig_type == 'table' then
        copy = {}
        for orig_key, orig_value in next, orig, nil do
            copy[TableCopy(orig_key)] = TableCopy(orig_value)
        end
        setmetatable(copy, TableCopy(getmetatable(orig)))
    else
        copy = orig
    end
    return copy
end
```

**Comment by Nitesam** [comment]
Made some update and translated comments for better understanding for non italian people, code now should work, gonna add a section on config to implement personal dispatch system.
